### ISSUE TITLE
Can we use it as a leak detector?

### ISSUE THREAD

**Issue by storozhukBM** [mitchellh/zig-libgc#1]

**Comment by storozhukBM** [comment]
Seems like bdwgc library itself supports this use case: https://github.com/ivmai/bdwgc/blob/master/doc/leak.md

**Comment by mitchellh** [comment]
https://github.com/mitchellh/zig-libgc/commit/c604b0d1f4d82b0b00b9b462b5d0726697dcf7b4

This should work. I didn't test it because unfortunately libgc just outputs to stderr and I didn't want to try to replace stderr to write the test yet.
